services:
  postgres:
    image: postgres:17
    container_name: travelhub-postgres
    environment:
      POSTGRES_DB: travelhub
      POSTGRES_USER: travelhub
      POSTGRES_PASSWORD: travelhub
    ports:
      - "5432:5432"
    volumes:
      - travelhub-postgres-data:/var/lib/postgresql/data

volumes:
  travelhub-postgres-data: